name: Build DGL from source

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_version:
        description: 'DGL version tag (e.g. v2.2.1). Leave empty to use latest release from upstream.'
        required: false
        default: ''

env:
    PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        cuda: [false, true]
        exclude:
          - os: macos-latest
            cuda: true

    env:
      DGL_BUILD_CPU: "ON"
      DGL_BUILD_CUDA: ${{ matrix.cuda }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Clone DGL repo with submodules
        run: |
          git clone --recurse-submodules https://github.com/dmlc/dgl.git dgl-src
          cd dgl-src
          git submodule update --init --recursive

        
      - name: Determine DGL version
        id: dgl_version
        run: |
          if [ -n "${{ github.event.inputs.build_version }}" ]; then
            TAG=${{ github.event.inputs.build_version }}
            echo Using Tag $TAG from input
          else
            TAG=$(git tag -l --sort=-taggerdate |tail -1)
            echo Using Tag $TAG from upstream release
          fi
          # pin to output as 
          # ${{ steps.dgl_version.outputs.TAG }}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

        working-directory: dgl-src
        shell: bash
        
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake
          brew install libuv
          brew install openssl zlib
          brew install llvm
          brew install lld
          pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1
          # Add LLVM clang to PATH for convenience
          echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> "$GITHUB_ENV"
          xcode-select --install || true


      - name: Install Dependencies (Windows, CPU-only)
        if: runner.os == 'Windows' && env.DGL_BUILD_CUDA == 'false'
        run: |
          
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install visualstudio2019buildtools -y
          pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cpu
        shell: bash

      - name: Install Dependencies (Windows, CUDA)
        if: runner.os == 'Windows' && env.DGL_BUILD_CUDA == 'true'
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install visualstudio2019buildtools -y
          choco install cuda -y
          pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124
        shell: bash

      - name: Build DGL (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir build && cd build
          
          # echo "LDFLAGS='-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/libomp/lib'" >> "$GITHUB_ENV"
          # echo "CPPFLAGS='-I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/libomp/include'" >> "$GITHUB_ENV"
          
          # cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DUSE_LIBXSMM=OFF -DUSE_OPENMP=OFF -DUSE_EPOLL=OFF ..
          # cmake --build . --config Release -- -j$(sysctl -n hw.ncpu)

          cmake -DUSE_OPENMP=off -DUSE_LIBXSMM=OFF -DUSE_EPOLL=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
          make -j$(sysctl -n hw.ncpu)
          cd ../python
          python setup.py install
          # Build Cython extension
          python setup.py build_ext --inplace
        working-directory: dgl-src
        shell: bash

      - name: Build DGL (Windows)
        if: runner.os == 'Windows'
        run: |
            MD build
            CD build
            cmake -DCMAKE_CXX_FLAGS="/DDGL_EXPORTS" -DCMAKE_CONFIGURATION_TYPES="Release" -DDMLC_FORCE_SHARED_CRT=ON ${{ matrix.cuda && '-DUSE_CUDA=ON' || '' }} .. -G "Visual Studio 16 2019"
            msbuild dgl.sln /m
        working-directory: dgl-src
        shell: powershell

      - name: Build Python Wheel
        run: |
          cd python
          python setup.py bdist_wheel
        working-directory: dgl-src
        shell: bash

      - name: Package Artifacts
        run: |
          TAG="${{ steps.dgl_version.outputs.TAG }}-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.cuda && '-cuda' || 'cpu' }}"
          mkdir -p artifacts
          cp python/dist/dgl*.whl artifacts/
          cd artifacts
          zip -r dgl-${TAG}.zip .
        working-directory: dgl-src
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dgl-${{ steps.dgl_version.outputs.TAG }}-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.cuda && '-cuda' || 'cpu' }}
          path: dgl-src/artifacts/dgl-*.zip
