name: Build DGL from source

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_version:
        description: 'DGL version tag (e.g. v2.2.1). Leave empty to use latest release from upstream.'
        required: false
        default: ''

env:
    PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        # arch: [x64, arm64]
        cuda: [false, true]
        exclude:
          - os: macos-latest
            cuda: true

    env:
      DGL_BUILD_CPU: "ON"
      DGL_BUILD_CUDA: ${{ matrix.cuda }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSVC++ environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Clone DGL repo with submodules
        run: |
          git clone --recurse-submodules https://github.com/dmlc/dgl.git dgl-src
          cd dgl-src
          git submodule update --init --recursive

        
      - name: Determine DGL version
        id: dgl_version
        run: |
          if [ -n "${{ github.event.inputs.build_version }}" ]; then
            TAG=${{ github.event.inputs.build_version }}
            echo Using Tag $TAG from input
          else
            TAG=$(git tag -l --sort=-taggerdate |tail -1)
            echo Using Tag $TAG from upstream release
          fi
          # pin to output as 
          # ${{ steps.dgl_version.outputs.TAG }}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

          git checkout $TAG

        working-directory: dgl-src
        shell: bash
        
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake
          brew install libuv
          brew install gnu-sed
          # brew install openssl zlib
          # brew install llvm libomp
          # brew install lld
          # brew install gcc@9
          # brew link --force libomp
          # brew install libomp
          pip install --upgrade pip wheel
          pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1
          # Add LLVM clang to PATH for convenience
          # echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> "$GITHUB_ENV"
          xcode-select --install || true

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          if [ "${{ env.DGL_BUILD_CUDA }}" == 'true' ]; then
            echo Installing CUDA as env.DGL_BUILD_CUDA = ${{ env.DGL_BUILD_CUDA }}
            choco install cuda -y
          fi
          pip install --upgrade pip wheel
          pip install -v torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/${{ matrix.cuda && 'cu124' || 'cpu' }}
        shell: bash

      - name: Build DGL (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir build
          cd build
          
          # disable graphbolt omp
          # see https://github.com/dmlc/dgl/issues/7833
          gsed -i 's/option(USE_OPENMP "Use OpenMP for graphbolt" ON)/option(USE_OPENMP "Use OpenMP for graphbolt" OFF)/g' ../graphbolt/CMakeLists.txt
          echo List parent:
          ls ..
          echo List graphbolt
          ls ../graphbolt
          echo Check Gsed mod: 
          grep "Use OpenMP for graphbolt" ../graphbolt/CMakeLists.txt
          echo Run cmake
          cmake .. \
            -DUSE_LIBXSMM=OFF \
            -DUSE_EPOLL=OFF \
            -DUSE_OPENMP=OFF \
            -DBUILD_CPP_TEST=OFF \ 
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 
            
          make -j$(sysctl -n hw.ncpu)
          cd ../python
          python setup.py install
          # Build Cython extension
          python setup.py build_ext --inplace
        working-directory: dgl-src
        shell: bash

      - name: Build DGL (Windows)
        if: runner.os == 'Windows'
        run: |
            $env:PATH += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin"
            MD build
            CD build
            cmake -DCMAKE_POLICY_VERSION_MINIMUM="3.5" -DCMAKE_CXX_FLAGS="/DDGL_EXPORTS" -DCMAKE_CONFIGURATION_TYPES="Release" -DDMLC_FORCE_SHARED_CRT=ON ${{ matrix.cuda && '-DUSE_CUDA=ON' || '-DUSE_CUDA=OFF' }} .. -G "Visual Studio 17 2022"
            msbuild dgl.sln /m
        working-directory: dgl-src
        shell: powershell

      - name: Build Python Wheel
        run: |
          cd python
          python setup.py bdist_wheel
        working-directory: dgl-src
        shell: bash

      - name: Package Artifacts
        run: |
          TAG="${{ steps.dgl_version.outputs.TAG }}-${{ runner.os }}-${{ matrix.cuda && '-cuda' || 'cpu' }}"
          mkdir -p artifacts
          cp python/dist/dgl*.whl artifacts/
          cd artifacts
          zip -r dgl-${TAG}.zip .
        working-directory: dgl-src
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dgl-${{ steps.dgl_version.outputs.TAG }}-${{ runner.os }}-${{ matrix.cuda && '-cuda' || 'cpu' }}
          path: dgl-src/artifacts/dgl-*.zip
